### ISSUE TITLE
Can't return a JsonModel in Controller.

### ISSUE THREAD

**Issue by Huanga-IT-Solutions** [laminas/laminas-view#225]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.23.0 (my installed version)

#### Summary

Can't return a JsonModel in Controller. Laminas tries to render a View - Template. It seems that Laminas confuses the JsonModel for a ViewModel.

#### Current behavior

Code:
```

use Laminas\View\Model\JsonModel;
use Laminas\View\Model\ViewModel;

...

public function searchAction() {

        return new JsonModel([
            'msg' => 'test',
        ]);
    }
```

When I try to return a JsonModel, following fatal error message occurs:

[Screenshot from 2023-10-23 12-25-08](https://github.com/laminas/laminas-view/assets/93322076/731cb774-4bd2-47b6-b3be-f72f7d745771)

#### How to reproduce

I'm using Docker / Docker - Compose. Here is my Docker / Docker - Compose - File:

```
FROM php:7.4-apache

ARG mode="dev" 

RUN apt-get update \
 && apt-get install -y git zlib1g-dev libzip-dev libicu-dev libpng-dev wget \
 && docker-php-ext-configure intl \
 && docker-php-ext-install intl \
 && docker-php-ext-install pdo pdo_mysql \
 && docker-php-ext-install zip \
 && docker-php-ext-install gd \
 && docker-php-ext-install pcntl \
 && a2enmod rewrite \
 && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-available/000-default.conf \
 && mv /var/www/html /var/www/public \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt install nodejs -y
RUN apt-get install npm -y

RUN yes | pecl install xdebug-2.9.8

COPY php.ini /usr/local/etc/php/



WORKDIR /var/www

COPY . .

RUN if [ "$mode" = "prod" ] ; then composer install --no-dev; else composer install; fi
RUN npm install 

RUN apt-get update
RUN yes | apt-get install gnupg
RUN wget -O phive.phar "https://phar.io/releases/phive.phar"
RUN wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
RUN gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x6AF725270AB81E04D79442549D8A98B29B2D5D79
RUN gpg --verify phive.phar.asc phive.phar
RUN rm phive.phar.asc
RUN chmod +x phive.phar
RUN mv phive.phar /usr/local/bin/phive
RUN yes | phive install  phpdocumentor

COPY opcache.ini /usr/local/etc/php/conf.d/opcache.ini
RUN docker-php-ext-configure opcache --enable-opcache \
    && docker-php-ext-install opcache

RUN chmod -R 777 data/cache
```

```
version: '3.5'

services:

  laminas-app:
    container_name: laminas-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "87:80"
      - "9503:9502"
    volumes:
      - ./:/var/www
    depends_on:
      - laminas-mysql
    networks:
      - app_network

  laminas-mysql:
    container_name: laminas-mysql
    image: mariadb:10.4.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: r00tPW!/
      MYSQL_DATABASE: laminasdb
      MYSQL_USER: laminasuser
      MYSQL_PASSWORD: laminaspassword
    ports:
      - "3312:3306"
    networks:
      - app_network

  laminas-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: laminas-pma
    links:
        - laminas-mysql
    environment:
        PMA_HOST: laminas-mysql
        PMA_USER: root
        PMA_PASSWORD: r00tPW!/
    ports:
    - 8081:80
    networks:
    - app_network

networks:
  app_network:
```

#### Expected behavior

No Error Message, Return JSON - Response to Client.

Thanks for your Help :)
